<?xml version="1.0" encoding="utf-8"?><Database Name="hotel_db" Class="GuestClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\_data\hotel_db.mdf;Integrated Security=True" SettingsObjectName="DOAN.Properties.Settings" SettingsPropertyName="hotel_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Room_Info" Member="Room_Infos">
    <Type Name="Room_Info">
      <Column Name="FirstName" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NChar(13)" CanBeNull="true" />
      <Column Name="CheckIn" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CheckOut" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ChekOut" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="RoomID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoomStatus" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="RoomType" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="RoomPrice" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="RoomBed" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="FirstName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="PassWord" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="NChar(12)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>